variables:
  - group: Github-credentials
  - group: npm-config-artifactory
  - group: jira-e1platform
  - name: pluginName
    value: "kibana-prometheus-exporter"  # name of the plugin
  
name: "$(pluginName)"

resources:
  repositories:
    - repository: kibana
      type: github
      name: elastic/kibana
      endpoint: Germanedge
      ref: 'refs/heads/8.12'

pool:
  vmImage: "ubuntu-22.04"

steps:
- checkout: self
  fetchDepth: 0
  path: s
  persistCredentials: true
- script: | 
    mkdir -p $(Build.SourcesDirectory)/elastic/kibana
  displayName: Create s/elastic/kibana repository folder (workaround)
- checkout: kibana
  fetchDepth: 0
  path: s/elastic/kibana
- task: UseNode@1
  inputs:
    version: '18.x'
  displayName: 'Install Node.js'
- script:  |
    if ! [ -f ".npmrc" ]; then
      echo registry=$npm_config_registry > .npmrc && 
      echo _auth=$npm_config_auth >> .npmrc &&
      echo always-auth=$npm_config_always_auth >> .npmrc &
      echo email=$npm_config_email >> .npmrc;
    fi
  displayName: 'Provide npm login'
- script: |
    npm install -g yarn
  displayName: 'Install Yarn'
- script: |
    yarn install
  displayName: 'yarn install plugin'
- script: |
    yarn --cwd s/elastic/kibana/ install
  displayName: 'yarn install kibana'
- script: |
    yarn build 
  displayName: 'yarn build'
#- script: |  
#    set -e
#    git config --global user.email "git@germanedge.com"
#    git config --global user.name "Continuous Integration"  
#  displayName: 'git config'
#  name: set_git_config
- script: |
    kibana_release=$(jq -r ".version" package.json)
    git tag $kibana_release
    git push --tags
  displayName: 'git add release tag'
