variables:
  - group: Github-credentials
  - group: artifactory-docker
  - group: jira-e1platform
  - name: imageName
    value: "kibana-prometheus-exporter"  # name of the image
  
name: "$(imageName) $(GitVersion.FullSemVer)"
  
resources:
  repositories:
    - repository: templates
      type: github
      name: Germanedge/azure-pipelines-templates
      endpoint: Germanedge
      ref: 'refs/heads/GE4-15356/pre-post-build-steps'
    - repository: kibana
      type: github
      name: elastic/kibana
      endpoint: Germanedge
      ref: 'refs/heads/8.12'

extends:
  template: azure-pipelines-docker-template.yml@templates
  parameters:
    gitPassword: $(gitPassword)
    gitUser: $(gitUser)
    stackDefinitionUpdating: false
    kubernetesManifestBuilding: true
    preBuildSteps:
      - checkout: self
        path: s
      - checkout: kibana
        path: elastic/kibana