variables:
  - group: Github-credentials
  - group: npm-config-artifactory
  - group: jira-e1platform
  - name: pluginName
    value: "kibana-prometheus-exporter"  # name of the plugin
  
name: "$(pluginName)"

resources:
  repositories:
    - repository: kibana
      type: github
      name: elastic/kibana
      endpoint: Germanedge
      ref: 'refs/heads/8.12'

pool:
  vmImage: "ubuntu-22.04"

steps:
- checkout: kibana
  fetchDepth: 0
  path: s
- checkout: self
  fetchDepth: 0
  path: s/kibana/plugins
  persistCredentials: true
- script: |
    nvm use
  displayName: 'Install Node.js'
- script:  |
    if ! [ -f ".npmrc" ]; then
      echo registry=$npm_config_registry > .npmrc && 
      echo _auth=$npm_config_auth >> .npmrc &&
      echo always-auth=$npm_config_always_auth >> .npmrc &
      echo email=$npm_config_email >> .npmrc;
    fi
  displayName: 'Provide npm login'
- script: |
    npm install -g yarn
  displayName: 'Install yarn'
- script: |
    yarn kbn bootstrap
  displayName: 'Bootstrap kibana'
- script: |
    cd plugins/$(pluginName)
    yarn install
    yarn build
  displayName: 'Build plugin'
#- script: |  
#    set -e
#    git config --global user.email "git@germanedge.com"
#    git config --global user.name "Continuous Integration"  
#  displayName: 'git config'
#  name: set_git_config
- script: |
    kibana_release=$(jq -r ".version" package.json)
    git tag $kibana_release
    git push --tags
  displayName: 'git add release tag'
